### ISSUE TITLE
Idea: PoE Status

### ISSUE THREAD

**Issue by darkelphos** [vmakeev/hass_tplink_easy_smart#2]
Hi! The integration works perfect. I can enable/disable ports. However the PoE power still up. It would be possible to add the PoE sensors and options? Ideally I would like to turn PoE Status Enable or Disable by port in Home assistant.

In addition, it would be nice to see the System Port Limit, System Power Consumption, System Power Remain sensors. 
![image](https://user-images.githubusercontent.com/124827005/217930664-ce97f9a3-2d79-432a-976f-7856dd9d886a.png)

Many thanks!

**Comment by vmakeev** [comment]
Hi, thanks for a great idea!

I added some sensors, controls and services for PoE. Can you try installing [this pre-release version](https://github.com/vmakeev/hass_tplink_easy_smart/releases/tag/v0.2.0-rc1), and check if everything works for you, and if there are any inconveniences when using integration?

I would also be grateful if you tell me the model and hardware revision of your router, I will add it to the list of supported models

**Comment by darkelphos** [comment]
Hi vmakeev, thanks for the release!

My hardware version is: TL-SG1016PE 3.0 and it seems to be working perfect.

![image](https://user-images.githubusercontent.com/124827005/218274493-9cdabd9f-62c8-4db0-8698-c8d27656d628.png)

The button of PoE Enable works perfect. Now I can turn on and off my PoE devices in HA.

The only inconvenience when I use the integration is if I need to enter to the router to change some config beacuse it will log me out from the web browser. In order to configure the switch and to work peacefully, I need to stop the integration or change the update interval to prevent log outs.

Many thanks for your nice work!

**Comment by vmakeev** [comment]
You are welcome!

> I need to stop the integration or change the update interval to prevent log outs.

Unfortunately, yes. Authorization in the web interface is implemented by Tp-Link in a very specific way, and several users cannot work with it at the same time.

I use a workaround to configure the switch: `Easy Smart Configuration Utility`, which is available for free download on the [Tp-Link website](https://www.tp-link.com/en/support/download/tl-sg1016pe/v3/).

It uses a broadcast with simple static key encryption to communicate with the device, and, unlike the web interface, it gets along well with my integration.

Of course, configuring via the Web UI is more familiar, and in some cases more convenient, but so far I have not been able to achieve simultaneous integration in HA and web interface
