### ISSUE TITLE
DOES NOT CONNECT WITHTL-SG1016DE  &  TL-SG108E 

### ISSUE THREAD

**Issue by emilianogetino** [vmakeev/hass_tplink_easy_smart#6]
When I try to connect to one of those two models I get a "Can not authenticate" error.
With the TL-SG1016PE it works perfectly.
All the best.

**Comment by emilianogetino** [comment]
I'll send you what you asked for, if you need anything else tell me.

<img width="249" alt="error" src="https://user-images.githubusercontent.com/59792653/236672769-623e7d92-7942-465b-aa56-b12b7927ae01.PNG">

<img width="357" alt="log" src="https://user-images.githubusercontent.com/59792653/236672783-9b67a51f-aac5-4894-bb5c-e8c652f63abb.PNG">

2023-05-07 12:06:50.893 ERROR (MainThread) [homeassistant.util.logging] Exception in async_write_ha_state when dispatching 'systemmonitor_update': ()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'off'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.process_octave_cli has device class None, state class measurement unit None and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: off (<class 'str'>)


[html.zip](https://github.com/vmakeev/hass_tplink_easy_smart/files/11414786/html.zip)

Thank you.

**Comment by vmakeev** [comment]
I apologize for a possibly stupid question: do these routers definitely have a web interface? Can you configure them without using the Easy Smart utility, just from the browser? Are their web interfaces accessible by the specified IP addresses from the browser?

**Comment by emilianogetino** [comment]
yes, of course, both switches have web interface and are accessed via web browser and tplink utility.
In the previous post I attached the html file with said access web page, the "html.zip" file, I compressed it so that I could attach it.
Anything you need I can provide.
Greetings, thank you for your time and your work.

**Comment by vmakeev** [comment]
I'm afraid that I initially chose the wrong way to develop the component. Maybe I should have tried using the protocol that the Easy Smart Configuration Utility uses. Instead, I focused on trying to use GET/POST requests and then parsing the resulting html pages. 

Apparently, different switch models have different behavior and different page layout, which prevents the component from being universal.

Perhaps I will try to add support for the broadcast protocol used in EasySmart to the component, but it is difficult for me to predict when this will be implemented
